package com.mycompany.myapp;


import com.codename1.io.Log;
import com.codename1.ui.Form;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.ui.Button;
import static com.codename1.ui.CN.getCurrentForm;
import com.codename1.ui.Component;
import static com.codename1.ui.Component.CENTER;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.TextField;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import Entities.User;
import guis.Affichage;
import guis.HomeForm;
import guis.Inscription;
import java.io.IOException;
import java.util.ArrayList;
import service.UserService;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    public static User use;
    public static ArrayList<User> user = new ArrayList<>();
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/RonRonTheme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start() {
      /*  if (current != null) {
            current.show();
            return;
        } */
      //  HomeForm h = new HomeForm();
      //  h.getF().show();
     //////////////////////////////////////////
    Form f = new Form("Login",new FlowLayout(Component.CENTER,CENTER));
    Container C5=new Container(new BoxLayout(BoxLayout.Y_AXIS));
         
            TextField tfUsername= new TextField("","Username");
            TextField tfPassword = new TextField("","Password");
            Button btnLog= new Button("Log In");
            C5.add(tfUsername);
            C5.add(tfPassword);
            C5.add(btnLog);
            Button  inscript=new Button("S'inscrire");
            inscript.addActionListener((e)->{
            Inscription a = null;
            try {
                a = new Inscription();
                 a.getF().show();
            } catch (IOException ex) {
              //  Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
            C5.add(inscript);
        f.add(C5);
        f.show();
        btnLog.addActionListener((e)->{
            UserService a1 = new UserService();
            ArrayList<User> lis= a1.LoggedUser(tfUsername.getText());
           if(!(lis.isEmpty()) &&!(tfPassword.getText().isEmpty()) && !(tfUsername.getText().isEmpty())){
               for(int i=0; i<lis.size()  ;i++){
                  
                        HomeForm h = new HomeForm(lis.get(i).getId());
                        h.getF().show();
                       MyApplication.user = lis;
                        
                }
            }else{
             Dialog.show("Erreur", "login ou mdp incorrect ","ok",null);
            }
      
        });
     /////////////////////////////////////////////
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }
}
